<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TestNG Test Group"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="1.008">
  <properties />
            <testcase name="firstTestCase" time="1.008" classname="com.servicenow.zProgress.PackOne.demoOne">
                <failure type="org.testng.internal.thread.ThreadTimeoutException"
                  message="Method org.testng.internal.TestNGMethod.firstTestCase() didn&apos;t finish within the time-out 1000"
              >
<![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.firstTestCase() didn't finish within the time-out 1000
  java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signalAll(AbstractQueuedSynchronizer.java:1957)
  java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:716)
  java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1014)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="secondTestCase" time="0.000" classname="com.servicenow.zProgress.PackOne.demoOne" />
      
</testsuite>
